import { AppContainer, NavigationBar } from '@upskill-app/ui/web';

import './global.css';

import { NextUIProvider } from '@nextui-org/react';

export const metadata = {
  title: 'Welcome to web-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body>
        <NextUIProvider>
          <NavigationBar />
          <AppContainer>{children}</AppContainer>
        </NextUIProvider>
      </body>
    </html>
  );
}
