import {
  AppContainer,
  AppFooter,
  AppUiProvider,
  NavigationBar,
} from '@upskill-app/ui/web';

import './global.css';

export const metadata = {
  title: 'Welcome to web-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body>
        <AppUiProvider>
          <NavigationBar />
          <AppContainer>{children}</AppContainer>
          <AppFooter />
        </AppUiProvider>
      </body>
    </html>
  );
}
