import {
  AppContainer,
  AppFooter,
  AppUiProvider,
  NavigationBar,
  Toaster,
} from '@upskill-app/ui/web';

import './styles/global.css';

import { ComponentWithChildren } from '@upskill-app/shared';

export const metadata = {
  title: 'Welcome to web-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: ComponentWithChildren) {
  return (
    <html lang="en" className="dark">
      <body>
        <AppUiProvider>
          <NavigationBar />
          <AppContainer>{children}</AppContainer>
          <AppFooter />
        </AppUiProvider>
      </body>
      <Toaster />
    </html>
  );
}
